### ISSUE TITLE
Incomplete GSM alphabet

### ISSUE THREAD

**Issue by piwel** [trt2/gsm-charset-utils#1]
Hi

According to [Wikipedia](https://en.wikipedia.org/wiki/GSM_03.38#GSM_7-bit_default_alphabet_and_extension_table_of_3GPP_TS_23.038_/_GSM_03.38), the alphabet is not exactly the same.

You have difference on char \u00A0 (non-breaking space - not in the GSM table), \u00C7 (Ç, missing in yours) but \u00E7 (ç) is not in the GSM table. 

https://github.com/trt2/gsm-charset-utils/blob/159ea821095722a969f3e26ef0c5cb5183fd8085/src/SmsUtil.js#L14

**Comment by trt2** [comment]
Thanks for reporting this.

\u00a0 should not be part of the valid characters, so I will remove this.

I believe the characters were initially based on information found here: https://www.unicode.org/Public/MAPPINGS/ETSI/GSM0338.TXT

This lists the lower case ç instead of upper case, but this seems to be in disagreement with most information I could find, so I will change this as well.

**Comment by trt2** [comment]
Fixed in 6d2dcc871757f6ab6fc6736678b1d075c6a3b808.
